const sharp = require('sharp');
const fs = require('fs/promises');
const path = require('path');
const W=1080,H=1350,OUT='output/fliers',G='#E4B03A';
const logo='assets/logo_transparent.png';
const items=[
['attendees-01-grand-carnival','FOR EVERYONE','carnival_animal_parade.jpg','FEEL THE|CARNIVAL','Culture, music, food and the finest of Nigerian livestock.','YOUR FREE GATE PASS','pass.livestockcarnival.ng'],
['attendees-02-family-celebration','BRING THE WHOLE FAMILY','family_petting_zoo.jpg','A CARNIVAL|LIKE NO OTHER','Meet the animals. Taste the flavours. Celebrate together.','CLAIM YOUR FREE PASS','pass.livestockcarnival.ng'],
['b2b-01-trade-connections','FOR BUYERS • INVESTORS • INDUSTRY','digital_etag.jpg','WHERE LIVESTOCK|MEETS OPPORTUNITY','Buyer-supplier matchmaking • investment • trade connections','MEET YOUR NEXT PARTNER','livestockcarnival.ng'],
['b2b-02-future-of-trade','THE FUTURE OF LIVESTOCK TRADE','hqi_cold_chain.jpg','CONNECT.|TRADE. GROW.','Discover innovation, investment and new routes to market.','JOIN THE TRADE EXCHANGE','livestockcarnival.ng'],
['vendors-01-showcase-your-brand','CALLING ALL VENDORS & EXHIBITORS','abuja_carnival_entrance.jpg','PUT YOUR|BRAND IN THE|SPOTLIGHT','Meet new customers at Nigeria’s grand livestock carnival.','BOOK YOUR EXHIBITOR SPACE','vendors.livestockcarnival.ng'],
['vendors-02-bring-your-best','FOOD • FASHION • AGRITECH • CRAFT','suya_open_flame.jpg','BRING YOUR BEST.|MEET YOUR MARKET.','Showcase your offer. Make connections. Be part of the buzz.','VENDOR REGISTRATION','vendors.livestockcarnival.ng'],
['herders-01-pride-of-the-herd','PASTORALISTS • BREEDERS • HERDERS','parade_camel.jpg','YOUR HERD.|YOUR HERITAGE.|YOUR MOMENT.','Showcase your breeds • compete • connect • celebrate.','TAKE YOUR PLACE AT THE CARNIVAL','livestockcarnival.ng'],
['herders-02-pastoralist-forum','A NATIONAL GATHERING FOR HERDERS','livestock_goat_sheep.jpg','CELEBRATE YOUR BREED.|SHAPE WHAT’S NEXT.','Livestock judging • pastoralist forum • cooperative grants','JOIN THE NATIONAL GATHERING','livestockcarnival.ng'],
['sponsors-01-partner-with-impact','PARTNERSHIP OPPORTUNITY','abuja_carnival_entrance.jpg','PUT YOUR BRAND|AT THE HEART OF IT.','Partner with a national celebration of livestock, culture and enterprise.','SPONSORSHIP ENQUIRIES','sponsors@livestockcarnival.ng'],
['sponsors-02-power-the-next-chapter','FOR BRANDS • INSTITUTIONS • INDUSTRY','cultural_festival_party.jpg','POWER THE NEXT|CHAPTER OF LIVESTOCK.','Connect your brand with the people and ideas shaping the sector.','EXPLORE PARTNERSHIP','sponsors@livestockcarnival.ng']
];
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function svg(item, photo, mark) {
 const title=item[3].split('|'), y=630, sz=title.some(x=>x.length>20)?61:74;
 const t=title.map((x,i)=>'<text x="82" y="'+(y+i*83)+'" font-family="Arial,Helvetica,sans-serif" font-size="'+sz+'" font-weight="900" letter-spacing="-2" fill="#FFFDF7">'+esc(x)+'</text>').join('');
 let desc=item[4].split(' '), lines=[], line=''; for(const w of desc){if((line+' '+w).length>43&&line){lines.push(line);line=w}else line+=(line?' ':'')+w} if(line)lines.push(line);
 const d=lines.slice(0,2).map((x,i)=>'<text x="84" y="'+(y+title.length*83+5+i*34)+'" font-family="Arial,sans-serif" font-size="24" fill="#F4F1E6">'+esc(x)+'</text>').join('');
 return '<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><defs><linearGradient id="shade" x2="0" y2="1"><stop stop-color="#031108" stop-opacity=".08"/><stop offset=".38" stop-color="#031108" stop-opacity=".12"/><stop offset=".62" stop-color="#04130B" stop-opacity=".94"/><stop offset="1" stop-color="#06150D"/></linearGradient><linearGradient id="base" x2="1" y2="1"><stop stop-color="#0D3922"/><stop offset="1" stop-color="#031009"/></linearGradient><style>.small{font-family:Arial,sans-serif;font-weight:800;letter-spacing:2px;fill:#F8E8B4}</style><clipPath id="photo"><rect width="1080" height="840"/></clipPath><clipPath id="photoAlt"><rect x="245" y="235" width="770" height="575" rx="34"/></clipPath></defs><rect width="1080" height="1350" fill="url(#base)"/><image href="data:image/jpeg;base64,'+photo+'" width="1080" height="840" preserveAspectRatio="xMidYMid slice" clip-path="url(#photo'+(item[0].includes('-02-')?'Alt':'')+')"/><rect width="1080" height="1350" fill="url(#shade)"/><path d="M0 830 Q270 785 540 824 T1080 810" fill="none" stroke="'+G+'" stroke-width="3"/><rect x="35" y="35" width="1010" height="1280" rx="22" fill="none" stroke="'+G+'" stroke-width="2" opacity=".8"/><rect x="51" y="51" width="978" height="1248" rx="16" fill="none" stroke="#FFF3CC" opacity=".35"/><image href="data:image/png;base64,'+mark+'" x="76" y="61" width="162" height="118" preserveAspectRatio="xMidYMid meet"/><text x="1000" y="92" text-anchor="end" class="small" font-size="14">NIGERIA • 2026</text><text x="1000" y="128" text-anchor="end" font-family="Georgia,serif" font-size="21" font-style="italic" fill="#F8E8B4">The Golden Camel &amp; Cow Carnival</text><path d="M82 208h44" stroke="'+G+'" stroke-width="3"/><text x="141" y="215" class="small" font-size="15">'+esc(item[1])+'</text><text x="83" y="564" font-family="Georgia,serif" font-size="34" font-style="italic" fill="'+G+'">✦  ◆  ✦</text>'+t+d+'<rect x="82" y="1000" width="916" height="70" rx="6" fill="'+G+'"/><text x="540" y="1044" text-anchor="middle" font-family="Arial,sans-serif" font-size="21" font-weight="900" letter-spacing="1.5" fill="#09150C">'+esc(item[5])+'</text><text x="540" y="1094" text-anchor="middle" font-family="Arial,sans-serif" font-size="21" font-weight="700" fill="#FFFDF7">'+esc(item[6])+'</text><path d="M335 1183h70M675 1183h70" stroke="'+G+'" stroke-width="2"/><text x="540" y="1190" text-anchor="middle" class="small" font-size="15">21–23 NOVEMBER 2026</text><text x="540" y="1230" text-anchor="middle" font-family="Arial,sans-serif" font-size="16" font-weight="600" fill="#E7E3D6">ABUJA NATIONAL GROUNDS · OLD PARADE GROUND, FCT</text></svg>';
}
(async()=>{await fs.mkdir(OUT,{recursive:true});const mark=await sharp(logo).resize(420,300,{fit:'inside'}).png().toBuffer();for(const item of items){const photo=await sharp('assets/'+item[2]).resize(1080,840,{fit:'cover'}).jpeg({quality:90}).toBuffer();await sharp(Buffer.from(svg(item,photo.toString('base64'),mark.toString('base64')))).png().toFile(path.join(OUT,item[0]+'.png'));console.log(item[0]);}})().catch(e=>{console.error(e);process.exit(1)});


