import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'How the Renewed Hope National Livestock Carnival website handles personal information and browser notifications.',
};

const sections = [
  { title: 'Who is responsible', body: <>This website is operated for the Renewed Hope National Livestock Carnival 2026 by its organizers. For privacy questions or requests, contact <a className="font-semibold text-[#1E4D38] underline" href="mailto:info@livestockcarnival.ng">info@livestockcarnival.ng</a> or call <a className="font-semibold text-[#1E4D38] underline" href="tel:+2349014740776">09014740776</a>.</> },
  { title: 'Information we handle and why', body: <>If you apply for press accreditation, we receive your name, organization, email address, National Identification Number (NIN), and the PDF credential you upload. We use these details to review accreditation and administer event access. The application and credential are intended to be removed after the review period and event through scheduled cleanup. Please submit only the information requested for the application. You may contact us to ask for deletion sooner, subject to applicable recordkeeping requirements.</> },
  { title: 'Support and staff accounts', body: <>If you use live support, the service processes your account name, email, profile image (if supplied by your sign-in provider), and messages so staff can respond. Staff CMS accounts process identity, email, role, and assigned permissions to operate the website. These details are limited to the support or site administration purpose for which they were provided.</> },
  { title: 'Browser push notifications', body: <>Push notifications are optional. The browser asks for permission only after you choose “Get updates.” If you subscribe, we store the browser push endpoint and encryption keys needed to send official carnival announcements. The browser and its push service (such as Apple, Google, or Mozilla) also process delivery information. We keep a subscription until you unsubscribe or the push service reports it is no longer valid. We retain campaign content and delivery totals for up to 90 days. To limit automated abuse, we temporarily retain a one-way hash of a network address for subscription rate-limiting, then delete it. You can unsubscribe using the control at the bottom of this website or revoke the permission in your browser settings. On iPhone and iPad, Web Push is available to web apps added to the Home Screen.</> },
  { title: 'Service providers and disclosures', body: <>Supabase provides the app’s database, authentication, and file storage. The site is hosted through Hostinger. Google provides sign-in when you choose Google authentication, and its satellite imagery is optional and loads only after you choose “Load map imagery.” When imagery is loaded, Google receives the network request and may process information such as your IP address and browser details under its <a className="font-semibold text-[#1E4D38] underline" href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Privacy Policy</a>. Browser push services (for example, Apple, Google, or Mozilla) deliver notifications after you subscribe. Supabase publishes its current <a className="font-semibold text-[#1E4D38] underline" href="https://supabase.com/legal/customer-resources/subprocessor-list" target="_blank" rel="noreferrer">subprocessor list</a>. We do not sell personal information. We share information with providers needed to run the site, authorized staff, or where required by law. Providers may process information outside Nigeria; the organizer should confirm the applicable transfer safeguards and provider terms.</> },
  { title: 'Cookies, external content, and AI', body: <>The site does not currently include advertising pixels or third-party analytics. It uses browser storage for interface preferences and notification opt-in state. The Google satellite map is not contacted until you choose to load its imagery. This site does not use visitor submissions to train an AI model.</> },
  { title: 'Your choices, export, and deletion', body: <>Subject to applicable law, you may request access to or a copy of your personal information, correction, deletion, restriction, or portability, object to processing, or withdraw consent where processing relies on consent. Email <a className="font-semibold text-[#1E4D38] underline" href="mailto:info@livestockcarnival.ng?subject=Personal%20data%20request">info@livestockcarnival.ng</a> with “Personal data request” in the subject and say whether you want access/export, correction, or deletion. Do not include your NIN or credential in the first email. We may ask for proportionate information to verify your identity and locate the relevant record. Requests are handled subject to applicable law and any lawful retention obligations. The Nigeria Data Protection Act 2023 is available on the <a className="font-semibold text-[#1E4D38] underline" href="https://ndpc.gov.ng/wp-content/uploads/2024/03/Nigeria_Data_Protection_Act_2023.pdf" target="_blank" rel="noreferrer">NDPC website</a>. If you remain dissatisfied, you may lodge a complaint with the <a className="font-semibold text-[#1E4D38] underline" href="https://ndpc.gov.ng/" target="_blank" rel="noreferrer">Nigeria Data Protection Commission</a> or contact it at <a className="font-semibold text-[#1E4D38] underline" href="mailto:info@ndpc.gov.ng">info@ndpc.gov.ng</a>.</> },
  { title: 'Security and policy changes', body: <>We use access controls and private storage for restricted information. No internet service can guarantee absolute security. We may update this notice when our practices or legal requirements change; the current version will be published on this page.</> },
];

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#FBFBFA] px-5 pb-20 pt-28 text-[#17251D] sm:px-8"><article className="mx-auto max-w-4xl"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#8D6B1B]">Legal information · Last updated 8 October 2026</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Privacy Policy</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[#59635D]">This notice explains how the Renewed Hope National Livestock Carnival website handles personal information. It applies to this website and its browser notifications, not the separate pass or vendor portals. Those portals have their own privacy notices and terms. This notice describes current website practices under the Nigeria Data Protection Act 2023.</p><div className="mt-10 divide-y divide-[#E4E9E3] rounded-2xl border border-[#E1E7E0] bg-white px-5 sm:px-8">{sections.map((section) => <section key={section.title} className="py-6"><h2 className="text-lg font-extrabold">{section.title}</h2><p className="mt-2 text-sm leading-7 text-[#4B5563]">{section.body}</p></section>)}</div><p className="mt-8 text-xs text-[#68746C]">For event admission, registration, or vendor transactions, review the relevant portal’s own privacy notice. <Link href="/terms" className="font-semibold text-[#1E4D38] underline">Read the Website Terms of Use</Link>.</p></article></main>;
}
